
{ 
  'root_dir':,
  'classifiers':[],
  'datasets':[],
  'data_dir':'',
  'model_dir':'',
  'result':{'figure_path':'',
            'saliency_map_path':'',
            'others_path':''},
  'evaluate':{'mask':{'batch_size':,
                      'scale':,
                      'smooth':,
                      'smoothing_window':[],
                      'max_rise':,
                      'max_fall':,
                      ''

                    },
              'N':
              }



}

